
package br.com.fws.appointment.resource;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClientService", targetNamespace = "http://resource.appointment.fws.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClientService {


    /**
     * 
     * @param clientData
     * @return
     *     returns br.com.fws.appointment.resource.ClientList
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "GetClientByFilter")
    @WebResult(name = "Clients", targetNamespace = "")
    @RequestWrapper(localName = "GetClientByFilter", targetNamespace = "http://resource.appointment.fws.com.br/", className = "br.com.fws.appointment.resource.GetClientByFilter")
    @ResponseWrapper(localName = "GetClientByFilterResponse", targetNamespace = "http://resource.appointment.fws.com.br/", className = "br.com.fws.appointment.resource.GetClientByFilterResponse")
    @Action(input = "http://resource.appointment.fws.com.br/ClientService/GetClientByFilterRequest", output = "http://resource.appointment.fws.com.br/ClientService/GetClientByFilterResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://resource.appointment.fws.com.br/ClientService/GetClientByFilter/Fault/Exception")
    })
    public ClientList getClientByFilter(
        @WebParam(name = "ClientData", targetNamespace = "")
        Client clientData)
        throws Exception_Exception
    ;

    /**
     * 
     * @param parameters
     * @param token
     * @return
     *     returns br.com.fws.appointment.resource.RegisterResponse
     * @throws AuthorizationException
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "Register")
    @WebResult(name = "RegisterResponse", targetNamespace = "http://resource.appointment.fws.com.br/", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://resource.appointment.fws.com.br/ClientService/RegisterRequest", output = "http://resource.appointment.fws.com.br/ClientService/RegisterResponse", fault = {
        @FaultAction(className = AuthorizationException.class, value = "http://resource.appointment.fws.com.br/ClientService/Register/Fault/AuthorizationException"),
        @FaultAction(className = Exception_Exception.class, value = "http://resource.appointment.fws.com.br/ClientService/Register/Fault/Exception")
    })
    public RegisterResponse register(
        @WebParam(name = "Register", targetNamespace = "http://resource.appointment.fws.com.br/", partName = "parameters")
        Register parameters,
        @WebParam(name = "Token", targetNamespace = "http://resource.appointment.fws.com.br/", header = true, partName = "Token")
        String token)
        throws AuthorizationException, Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns br.com.fws.appointment.resource.ClientList
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "GetAllClients")
    @WebResult(name = "Clients", targetNamespace = "")
    @RequestWrapper(localName = "GetAllClients", targetNamespace = "http://resource.appointment.fws.com.br/", className = "br.com.fws.appointment.resource.GetAllClients")
    @ResponseWrapper(localName = "GetAllClientsResponse", targetNamespace = "http://resource.appointment.fws.com.br/", className = "br.com.fws.appointment.resource.GetAllClientsResponse")
    @Action(input = "http://resource.appointment.fws.com.br/ClientService/GetAllClientsRequest", output = "http://resource.appointment.fws.com.br/ClientService/GetAllClientsResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://resource.appointment.fws.com.br/ClientService/GetAllClients/Fault/Exception")
    })
    public ClientList getAllClients()
        throws Exception_Exception
    ;

    /**
     * 
     * @param clientFilter
     * @return
     *     returns br.com.fws.appointment.resource.Client
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "GetClient")
    @WebResult(name = "Client", targetNamespace = "")
    @RequestWrapper(localName = "GetClient", targetNamespace = "http://resource.appointment.fws.com.br/", className = "br.com.fws.appointment.resource.GetClient")
    @ResponseWrapper(localName = "GetClientResponse", targetNamespace = "http://resource.appointment.fws.com.br/", className = "br.com.fws.appointment.resource.GetClientResponse")
    @Action(input = "http://resource.appointment.fws.com.br/ClientService/GetClientRequest", output = "http://resource.appointment.fws.com.br/ClientService/GetClientResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://resource.appointment.fws.com.br/ClientService/GetClient/Fault/Exception")
    })
    public Client getClient(
        @WebParam(name = "ClientFilter", targetNamespace = "")
        Client clientFilter)
        throws Exception_Exception
    ;

}
